version: '2'
services:
    rfr3-app:
        image: rfr3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfr3-mysql:3306/rfr3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfr3-mysql:
        extends:
            file: mysql.yml
            service: rfr3-mysql
